### ISSUE TITLE
Смарт-контракт не заработал

### ISSUE THREAD

**Issue by alex-devPY** [artyomLisovskij/solidity-erc20-token-bootstrap#2]
Здравствуйте,  загрузил Ваш контракт

https://ropsten.etherscan.io/address/0x3f9b70bb4710b189796bbedda965309ac1eadfca#code

При попытке отправить транзакцию  получилась ошибка

https://ropsten.etherscan.io/tx/0x558e8cdcd7f7089e0891d841acb36059772f9f71acec00108efd8f38fb23cb68

Там случайно не требуется что-то вроде

`function() external payable {
   
}`

чтобы принимать эфир?

**Comment by artyomLisovskij** [comment]
требуется. чтобы принимать эфир действительно необходимо добавть payable функцию, внутри которой производить конверсию eth в ваши токены и их начисление

**Comment by artyomLisovskij** [comment]
Согласно стандарта ERC20 прием ETH не входит в общий стандарт, поэтому в текущей реализации приема и конвертации эфира нет.

**Comment by alex-devPY** [comment]
Да, извиняюсь. Стандарт этого не описывает, не обратил сразу внимание. Хотя зря, на мой взгляд.
